name: Firebase Build And Preview

on:
  workflow_run:
    workflows: ["React Checks"]
    types:
      - completed

jobs:
  build-and-preview:
    name: Build React Artifact And Deploy Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KJBAPPS }}'
          projectId: kjbapps